baseURL: 'https://Rio-sh.github.io/riosh_works'
languageCode: ja
title: Rio-Sh Works
theme:
  - hugo-video
  - PaperMod
canonifyurls: true
publishDir: docs

params:
    homeInfoParams:
        Title: App
        Content: Each page has overview and link to a repository. 

    socialIcons: # optional
        - name: github
          url: "https://github.com/Rio-Sh"

